= JSON&AJAX&I18N
:source-highlighter: highlight.js
:source-language: java
:toc: left
:toc-title: JSON&AJAX&i18n
:toclevels: 3
:sectnums:

== JSON
=== 什么是JSON?
JSON (JavaScript Object Notation) 是一种轻量级的数据交换格式。易于人阅读和编写。同时也易于机器解析和生成。

JSON采用完全独立于语言的文本格式，而且很多语言都提供了对 json 的支持（包括 C, C++, C#, Java, JavaScript,Perl,Python等）。 这样就使得 JSON 成为理想的数据交换格式。

- json 是一种轻量级的数据交换格式
* 轻量级指的是跟 xml 做比较
* 数据交换指的是客户端和服务器之间业务数据的传递格式

=== JSON 在 JavaScript 中的使用
==== 定义
json 是由键值对组成，并且由大括号包围。每个键由引号引起来，键和值之间使用冒号进行分隔，多组键值对之间进行逗号进行分隔

----
var jsonObj = {
    "key1":12,
    "key2":"abc",
    "key3":true,
    "key4":[11,"arr",false],
    "key5":{
        "key5_1" : 551,
        "key5_2" : "key5_2_value"
    },
    "key6":[{
        "key6_1_1":6611,
        "key6_1_2":"key6_1_2_value"
    },{
        "key6_2_1":6621,
        "key6_2_2":"key6_2_2_value"
    }]
};
----

==== 访问
- json 本身是一个对象
- json 中的 key 我们可以理解为是对象中的一个属性
- json 中的 key 访问就跟访问对象的属性一样： json 对象.key

----
alert(typeof(jsonObj));// object json 就是一个对象
alert(jsonObj.key1); //12
alert(jsonObj.key2); // abc
alert(jsonObj.key3); // true
alert(jsonObj.key4);// 得到数组[11,"arr",false]
// json 中 数组值的遍历
for(var i = 0; i < jsonObj.key4.length; i++) {
alert(jsonObj.key4[i]);
}
alert(jsonObj.key5.key5_1);//551
alert(jsonObj.key5.key5_2);//key5_2_value
alert( jsonObj.key6 );// 得到 json 数组
// 取出来每一个元素都是 json 对象
var jsonItem = jsonObj.key6[0];
// alert( jsonItem.key6_1_1 ); //6611
alert( jsonItem.key6_1_2 ); //key6_1_2_value
----

==== JSON字符串和对象的互转
===== JSON的存在形式
- json 对象
- json 字符串

===== 使用
- 操作 json 中的数据时，需要 json 对象的格式
- 在客户端和服务器之间进行数据交换时，使用 json 字符串

===== 方法
- JSON.stringify() 把 json 对象转换成为 json 字符串
- JSON.parse() 把 json 字符串转换成为 json 对象

===== 示例
----
// 把 json 对象转换成为 json 字符串
var jsonObjString = JSON.stringify(jsonObj); // 特别像 Java 中对象的 toString
alert(jsonObjString)
// 把 json 字符串。转换成为 json 对象
var jsonObj2 = JSON.parse(jsonObjString);
alert(jsonObj2.key1);// 12
alert(jsonObj2.key2);// abc
----

=== JSON 在 java 中的使用
*需要导入类库：`gson-2.10.1.jar`*

主要方法: `gson.toJson(); gson.fromJson()`

==== javaBean 和 json 的互转
----
Worker worker = new Worker("monster", "man", 18);
Gson gson = new Gson();
String json = gson.toJson(worker);//将对象转换为json字符串
System.out.println(json);
Worker worker1 = gson.fromJson(json, Worker.class);//将json字符串转换为对象
System.out.println(worker1);
----

==== List 和 json 的互转
----
public class WorkerListType extends TypeToken<List<Worker>> {}
----
----
List<Worker> workers = new ArrayList<>();
workers.add(new Worker("monster", "man", 18));
workers.add(new Worker("tom", "man", 21));
Gson gson = new Gson();
String json = gson.toJson(workers);//将数组转换为json字符串
System.out.println(json);
//方法一：直接使用匿名内部类：
List<Worker> workers1 = gson.fromJson(json, new TypeToken<List<Worker>>() {}.getType());//将json字符串转换为数组
System.out.println(workers1);
//方法二：使用工具类:创建自定义 TypeToken 类：
List<Worker> workers2 = gson.fromJson(json, new WorkerListType().getType());
System.out.println(workers2);//打印数组
workers2.forEach(System.out::println);//遍历数组
----

==== map 和 json 的互转
----
Map<Integer, Worker> workerMap = new HashMap<>();
workerMap.put(1, new Worker("monster", "man", 18));
workerMap.put(2, new Worker("tom", "man", 21));
Gson gson = new Gson();
String json = gson.toJson(workerMap);//将集合转换为json字符串
System.out.println(json);

Map<Integer, Worker> workerMap1 = gson.fromJson(json, new TypeToken<Map<Integer, Worker>>() {}.getType());//将json字符串转换为集合
System.out.println(workerMap1);//打印集合
Worker monster = workerMap1.get(1);//打印集合中指定元素
System.out.println(monster);
----

== AJAX
=== 概述
AJAX 即 `Asynchronous Javascript And XML` (异步 JavaScript 和 XML)，是指一种创建交互式网页应用的网页开发技术。

- ajax 是一种浏览器通过 js 异步发起请求，局部更新页面的技术
- Ajax 请求的局部更新，浏览器地址栏不会发生变化
- 局部更新不会舍弃原来页面的内容

=== 原生 AJAX 请求
==== 代码实例
[,html]
----
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AJAX</title>
    <script>
        window.onload = function () {
            // 页面加载后，将点击事件绑定到按钮上
            document.getElementById("btn").onclick = function () {
                // 创建 XMLHttpRequest 对象
                var xmlHttpRequest = new XMLHttpRequest();
                // 配置 AJAX 请求，指定请求方法、URL、是否异步
                xmlHttpRequest.open("GET", "http://localhost:8080/rear_end/AjaxServlet", true);
                // 定义当 readyState 改变时的回调函数
                xmlHttpRequest.onreadystatechange = function () {
                    // 当 readyState 为 4（请求已完成） 并且 status 为 200（成功响应） 时
                    if (xmlHttpRequest.readyState == 4 && xmlHttpRequest.status == 200) {
                        // 解析服务器返回的 JSON 数据
                        var jsonObj = JSON.parse(xmlHttpRequest.responseText);
                        // 更新页面上 id 为 "result" 的元素内容
                        document.getElementById("result").innerHTML = "姓名：" + jsonObj.name + "性别：" + jsonObj.sex + "年龄:" + jsonObj.age;
                    }
                }
                // 发送 AJAX 请求
                xmlHttpRequest.send();
                // 更新页面上 id 为 "result1" 的元素内容
                document.getElementById("result1").innerHTML = "ajax请求完成";
            }
        }
    </script>
</head>
<body>
    <!-- 点击按钮触发 AJAX 请求 -->
    <button id="btn">ajax请求</button>
    <!-- 显示服务器返回的 JSON 数据 -->
    <div id="result"></div>
    <!-- 显示 AJAX 请求完成的提示 -->
    <div id="result1"></div>
</body>
</html>
----

----
@WebServlet(name = "AjaxServlet", value = "/AjaxServlet")
public class AjaxServlet extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        // 创建一个 Worker 对象
        Worker worker = new Worker("monster", "man", 18);
        try {
            // 模拟延迟 500 毫秒
            Thread.sleep(500);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        // 使用 Gson 将 Worker 对象转换为 JSON 字符串
        Gson gson = new Gson();
        String json = gson.toJson(worker);
        // 将 JSON 字符串作为响应返回给客户端
        response.getWriter().write(json);
    }
}
----

==== 参数说明
===== readyState
readyState 是表示当前请求的状态的属性。它有以下几个可能的值：

- 0：请求未初始化，尚未调用 open() 方法。
- 1：已经调用 open() 方法，但尚未调用 send() 方法。
- 2：已经调用 send() 方法，正在处理请求。
- 3：正在接收和解析响应数据。
- 4：已经完成响应的数据传输。

在大多数情况下，只需要关注 readyState 的值是否为 4，表示请求已经完成。

===== status
status 是在请求完成后表示 HTTP 响应状态的属性。它包含一个表示 HTTP 响应代码的数字。以下是一些常见的 HTTP 状态代码：

- 200：请求成功，表示响应正常。
- 404：未找到请求的资源。
- 500：服务器内部错误。

当使用 AJAX 进行请求时，可以使用 status 属性来检查服务器是否成功响应请求。

=== jQuery中的AJAX请求
==== $.ajax 方法
- `url` 表示请求的地址
- `type` 表示请求的类型 GET 或 POST 请求
- `data` 表示发送给服务器的数据，格式有两种：
* name=value&name=value
* {key:value}
- `success` 请求成功，响应的回调函数
- `dataType` 响应的数据类型，常用的数据类型有：
* `text` 表示纯文本
* `xml` 表示 xml 数据
* `json` 表示 json 对象

[,javascript]
----
$(function () {
    $("#btn").click(function () {
        $.ajax({
            url: "http://localhost:8080/rear_end/AjaxServlet",
            type: "get",
            data:{action:"jQueryAjax"},
            //或: data:"action=jQueryAjax",
            success: function (data) {
                $("#result").html("姓名：" + data.name + " 性别：" + data.sex + " 年龄:" + data.age);
            },
            dataType: "json"<1>
        });
    });
});
----
<1> 若使用text类型，需要将data转为json对象才能在回调函数中调用各个属性

==== $.get 和 $.post 方法
相比 $.ajax 方法少了参数`dataType`，注意语法也和 $.ajax 有些不同，变成了直接写值，不写属性名

- `url` 请求的 url 地址
- `data` 发送的数据
- `callback` 成功的回调函数
- `type` 返回的数据类型

[,javascript]
----
$("#getBtn").click(function(){
    $.get(
        "http://localhost:8080/16_json_ajax_i18n/ajaxServlet","action=jQueryGet",
        function(data){
            $("#msg").html("编号：" + data.id + " , 姓名：" + data.name);
        },
        "json"
    );
});
----

==== $.getJson 方法
相比 $.get 和 $.post 方法少了参数`type`

- `url` 请求的 url 地址
- `data` 发送给服务器的数据
- `callback` 成功的回调函数

[,javascript]
----
$("#getJSONBtn").click(function () {
    $.getJSON(
        "http://localhost:8080/16_json_ajax_i18n/ajaxServlet",
        "action=jQueryGetJSON",
        function (data) {
            $("#msg").html("编号：" + data.id + " , 姓名：" + data.name);
        }
    );
});
----

==== 表单序列化 serialize()
`serialize()` 可以把表单中所有表单项的内容都获取到，并以 `name=value&name=value` 的形式进行拼接。

.使用：把通过serialize()获取到的键值对发送给服务器
[,javascript]
----
$("#submit").click(function () {
    // 把参数序列化
    $.getJSON(
        "http://localhost:8080/16_json_ajax_i18n/ajaxServlet",
        "action=jQuerySerialize&" + $("#form01").serialize(),<1>
        function (data) {
            $("#msg").html("编号：" + data.id + " , 姓名：" + data.name);
        }
    );
});
----
<1> `"action=jQuerySerialize&"`: 注意此处末尾要加上 `&`

== I18N
=== 概述
- 国际化（Internationalization）指的是同一个网站可以支持多种不同的语言，以方便不同国家，不同语种的用户访问。
- 国际化的英文 Internationalization 拼写过长，简称 I18N。 Internationalization 这个单词，以 I 开头，以 N 结尾，而中间是 18 个字母，所以简写为 I18N。I18N 和国际化是一个意思。

=== 国际化三要素
==== ResourceBundle 资源包
- ResourceBundle.getBundle(baseName, locale)
* 该方法根据给定的 baseName 和 locale 读取对应配置文件，得到文字信息

- bundle.getString(key)
* 通过上个方法得到的对象调用getString获取该国家对应的语言信息

==== Locale对象
Locale 表示不同的时区, 位置, 语言

.例
- zh_CN 中国, 中文
- en_US 英文, 美国

==== Properties 后缀的配置文件
国家化配置文件命名规则： `baseName_lacale.properties`

.例：baseName 是 i18n
- 中文的配置文件名: `i18n_zh_CN.properties`
- 英文的配置文件名: `i18n_en_US.properties`

=== 简单代码示例
----
ResourceBundle i18n = ResourceBundle.getBundle("i18n", Locale.CHINA);
String username = i18n.getString("username");
String password = i18n.getString("password");
String age = i18n.getString("age");
System.out.println("用户名：" + username + " 密码:" + password + " 年龄:" + age);
----
.i18n_zh_CN.properties
----
username=用户名
password=密码
age=年龄
----

=== 页面国际化实例
==== 通过jsp脚本实现国际化
通过请求头或页面的语言切换选项获取Locale

.body标签内添加如下代码
[,jsp]
----
<%
    // 从请求头中获取 Locale 信息（语言）
    Locale locale = null;
    String country = request.getParameter("country");
    if ("cn".equals(country)) {
        locale = Locale.CHINA;
    } else if ("usa".equals(country)) {
        locale = Locale.US;
    } else {
        locale = request.getLocale();
    }
    System.out.println(locale);
    // 获取读取包（根据 指定的 baseName 和 Locale 读取 语言信息）
    ResourceBundle i18n = ResourceBundle.getBundle("i18n", locale);
%>
<a href="i18n.jsp?country=cn">中文</a>|
<a href="i18n.jsp?country=usa">english</a>
----
.对应文字处换成如下样式代码
[,jsp]
----
<h1><%=i18n.getString("regist")%></h1>
<td><%=i18n.getString("username")%></td>
----

=== 通过 JSTL 标签库实现国际化
.引入标签库
----
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
----
.使用方法
----
<%--1 使用标签设置 Locale 信息--%>
<fmt:setLocale value="${param.locale}" />
<%--2 使用标签设置 baseName--%>
<fmt:setBundle basename=""/>
<%--3 输出指定 key 的国际化信息--%>
<fmt:message key="" />
----

----
<a href="i18n_fmt.jsp?locale=zh_CN">中文</a>|
<a href="i18n_fmt.jsp?locale=en_US">english</a>
----