= Java 8新特性
:source-highlighter: highlight.js
:source-language: java
:toc: left
:toc-title: Java 8新特性
:toclevels: 3
:sectnums:

== Java 8新特性简介
. 速度更快
. 代码更少(增加了新的语法：Lambda 表达式)
. 强大的 Stream API
. 便于并行
. 最大化减少空指针异常：Optional
. Nashorn引擎，允许在JVM上运行JS应用

== Lambda 表达式
=== 为什么使用 Lambda 表达式？
Lambda 是一个匿名函数，我们可以把 Lambda 表达式理解为是一段可以传递的代码（将代码像数据一样进行传递）。使用它可以写出更简洁、更灵活的代码。作为一种更紧凑的代码风格，使Java的语言表达能力得到了提升。

=== 格式
- 操作符：\-> +
该操作符被称为 Lambda 操作符或箭头操作符。
- 操作符左侧：指定 Lambda 表达式需要的参数列表。
+
TIP: 其实就是接口中的抽象方法的形参列表。
- 操作符右侧：指定 Lambda 体，是抽象方法的实现逻辑，也即Lambda 表达式要执行的功能。
+
TIP: 其实就是重写的抽象方法的方法体。

=== 语法
- 左边：lambda形参列表的参数类型可以省略(类型推断)；如果lambda形参列表只有一个参数，其一对()也可以省略。
+
NOTE: Lambda 表达式中的参数类型都是由编译器推断得出的。Lambda表达式中无需指定类型，程序依然可以编译，这是因为 javac 根据程序的上下文，在后台推断出了参数的类型。Lambda 表达式的类型依赖于上下文环境，是由编译器推断出来的。这就是所谓的“类型推断”。
- 右边：lambda体应该使用一对{}包裹；如果lambda体只有一条执行语句（可能是return语句），省略这一对{}和return关键字。

.例
----
// 语法格式一：无参，无返回值
Runnable r1 = () -> {System.out.println("Hello Lambda!");};

// 语法格式二：Lambda 需要一个参数，但是没有返回值
Consumer<String> com = (String str) -> {System.out.println(str);};

// 语法格式三：数据类型可以省略，因为可由编译器推断得出，称为“类型推断”
Consumer<String> com = (str) -> {System.out.println(str);};

// 语法格式四：Lambda 若只需要一个参数时，参数的小括号可以省略
Consumer<String> com = str -> {System.out.println(str);};

// 语法格式五：Lambda 需要两个或以上的参数，多条执行语句，并且可以有返回值
Comparator<Integer> com = (x,y) -> {
    System.out.println("实现函数式接口方法！");
    return Integer.compare(x,y);
};

// 语法格式六：当 Lambda 体只有一条语句时，return 与大括号若有，都可以省略
Comparator<Integer> com = (x,y) -> Integer.compare(x,y);
----

== 函数式(Functional)接口
=== 什么是函数式(Functional)接口?
. *只包含一个抽象方法的接口，称为函数式接口。*
. 可以通过 Lambda 表达式来创建该接口的对象。
+
NOTE: 若 Lambda 表达式抛出一个受检异常(即：非运行时异常)，那么该异常需要在目标接口的抽象方法上进行声明。
. 函数式接口上可以使用 @FunctionalInterface 注解。
+
NOTE: 这样做可以检查它是否是一个函数式接口。同时 javadoc 也会包含一条声明，说明这个接口是一个函数式接口。
. 在java.util.function包下定义了Java 8 的丰富的函数式接口。

=== 如何理解函数式接口？
. Java从诞生日起就是一直倡导“一切皆对象”，在Java里面面向对象(OOP)编程是一切。但是随着python、scala等语言的兴起和新技术的挑战，Java不得不做出调整以便支持更加广泛的技术要求，也即java不但可以支持OOP还可以支持OOF（面向函数编程）。
. 在函数式编程语言当中，函数被当做一等公民对待。在将函数作为一等公民的编程语言中，Lambda表达式的类型是函数。但是在Java8中，有所不同。在Java8中，Lambda表达式是对象，而不是函数，它们必须依附于一类特别的对象类型——函数式接口。
. 简单的说，在Java8中，Lambda表达式就是一个函数式接口的实例。这就是Lambda表达式和函数式接口的关系。也就是说，只要一个对象是函数式接口的实例，那么该对象就可以用Lambda表达式来表示。
. 所以以前用匿名实现类表示的现在都可以用Lambda表达式来写。

=== Java 内置函数式接口
==== 四大核心函数式接口
[%header, cols="^.^2,^.^1,^.^1,^.^3"]
|===
|函数式接口|参数类型|返回类型|用途

|Consumer<T> 消费型接口|T|void
|对类型为T的对象应用操作。 +
包含方法：void accept(T t)

|Supplier<T> 供给型接口|无|T
|返回类型为T的对象。 +
包含方法：T get()

|Function<T,R> 函数型接口|T|R
|对类型为T的对象应用操作，并返回结果。结果是R类型的对象。 +
包含方法。R apply(T t)

|Predicate<T> 断定型接口|T|boolean
|确定类型为T的对象是否满足某约束，并返回boolean值。 +
包含方法：boolean test(T t)
|===

==== 其他函数式接口
[%header, cols="^.^2,^.^1,^.^1,^.^3"]
|===
|函数式接口|参数类型|返回类型|用途

|BiFunction<T,U,R>|T,U|R
|对类型为T,U参数应用操作，返回R类型的结果。 +
包含方法：R apply(T t,U u)

|UnaryOperator<T> Function子接口|T|T
|对类型为T的对象进行一元运算，并返回T类型的结果。 +
包含方法：T apply(T t)

|BinaryOperator<T> BiFunction子接口|T,T|T
|对类型为T的对象进行二元运算，并返回T类型的结果。 +
包含方法：T apply(T t1,T t2)

|BiConsumer<T,U>|T,U|void
|对类型为T,U参数应用操作。 +
包含方法：void accept(T t,U u)

|BiPredicate<T,U>|T,U|boolean
|包含方法：boolean test(T t,U u)

|ToIntFunction<T> +
ToLongFunction<T> +
ToDoubleFunction<T>|T
|int +
long +
double
|分别计算int、long、double值的函数

|IntFunction<R> +
LongFunction<R> +
DoubleFunction<R>
|int +
long +
double|R
|参数分别为int、long、double类型的函数
|===

====  接口用例
----
@Test
public void test2(){
    List<String> list = Arrays.asList("北京","南京","天津","东京","西京","普京");

    List<String> filterStrs = filterString(list, new Predicate<String>() {
        @Override
        public boolean test(String s) {
            return s.contains("京");
        }
    });

    System.out.println(filterStrs);


    List<String> filterStrs1 = filterString(list,s -> s.contains("京"));
    System.out.println(filterStrs1);
}

//根据给定的规则，过滤集合中的字符串。此规则由Predicate的方法决定
public List<String> filterString(List<String> list, Predicate<String> pre){

    ArrayList<String> filterList = new ArrayList<>();

    for(String s : list){
        if(pre.test(s)){
            filterList.add(s);
        }
    }

    return filterList;

}
----
== 方法引用，构造器、数组引用
=== 方法引用
==== 概述
-当要传递给Lambda体的操作已经有实现的方法时，就可以使用方法引用。
- 方法引用可以看做是Lambda表达式深层次的表达。换句话说，方法引用就是Lambda表达式，也就是函数式接口的一个实例，通过方法的名字来指向一个方法，可以认为是Lambda表达式的一个语法糖。

==== [[格式]]格式
使用操作符 “::” 将类(或对象)与方法名分隔开来。 +
有如下三种主要使用情况：

- `对象::实例方法名`
* `Consumer<String> con = str \-> System.out.println(str);` 等同于 `Consumer<String> con = System.out::println;`。

- `类::静态方法名`
* `Comparator<Integer> com = (t1,t2) \-> Integer.compare(t1,t2);` 等同于 `Comparator<Integer> com = Integer::compare;`。

- `类::实例方法名`
* `Comparator<String> com = (s1,s2) \-> s1.compareTo(s2);` 等同于 `Comparator<String> com = String :: compareTo;`。

==== 使用方式
实现接口的抽象方法的参数列表和返回值类型，必须与方法引用的
方法的参数列表和返回值类型保持一致。

IMPORTANT: 该方式针对以上<<格式>>中的前两种。

NOTE: **第三种格式的使用方式是：**函数式接口方法的第一个参数是需要引用方法的调用者，并且第二个参数是需要引用方法的参数(或无参数)。

=== 构造器引用
==== 格式
`ClassName::new`

* `Function<Integer,MyClass> func = n \-> new MyClass(n);` 等同于 `Function<Integer,MyClass> func = MyClass :: new;`。

==== 使用方式
与函数式接口相结合，自动与函数式接口中方法兼容。可以把构造器引用赋值给定义的方法，要求构造器参数列表要与接口中抽象方法的参数列表一致，且方法的返回值即为构造器对应类的对象。

=== 数组引用
==== 格式
`type[]::new`

* `Function<Integer,String[]> func = length \-> new String[length];` 等同于 `Function<Integer,String[]> func = String[]::new;`。

== Stream API
=== 概述
==== 引言
- Stream API ( java.util.stream) 把真正的函数式编程风格引入到Java中。这是目前为止对Java类库最好的补充，因为Stream API可以极大提供Java程序员的生产力，让程序员写出高效率、干净、简洁的代码。
- Stream 是 Java8 中处理集合的关键抽象概念，它可以指定你希望对集合进行的操作，可以执行非常复杂的查找、过滤和映射数据等操作。 使用Stream API 对集合数据进行操作，就类似于使用 SQL 执行的数据库查询。也可以使用 Stream API 来并行执行操作。简言之，Stream API 提供了一种高效且易于使用的处理数据的方式。

==== 什么是 Stream？
- Stream是数据渠道，用于操作数据源（集合、数组等）所生成的元素序列。
- 集合讲的是数据，Stream讲的是**计算**。

[NOTE]
====
- Stream 自己不会存储元素。
- Stream 不会改变源对象。相反，他们会返回一个持有结果的新Stream。
- Stream 操作是延迟执行的。这意味着他们会等到需要结果的时候才执行。
====

==== 为什么要使用Stream API？
实际开发中，项目中多数数据源都来自于Mysql，Oracle等。但现在数据源更多，有MongDB，Radis等，而这些NoSQL的数据就需要Java层面去处理。

==== Stream 和 Collection 集合的区别
Collection 是一种静态的内存数据结构，而 Stream 是有关计算的。前者是主要面向内存，存储在内存中，后者主要是面向 CPU，通过 CPU 实现计算。

=== Stream 的操作步骤
==== 创建 Stream
一个数据源（如：集合、数组），获取一个流。

===== 方式一：通过集合
Java8 中的 Collection 接口被扩展，提供了两个获取流的方法：

- default Stream<E> stream()：返回一个顺序流
- default Stream<E> parallelStream()：返回一个并行流

===== 方式二：通过数组
Java8 中的 Arrays 的静态方法 stream() 可以获取数组流：

- static <T> Stream<T> stream(T[] array)：返回一个流

重载形式，能够处理对应基本类型的数组：

- public static IntStream stream(int[] array)
- public static LongStream stream(long[] array)
- public static DoubleStream stream(double[] array)

===== 方式三：通过Stream的of()
可以调用Stream类静态方法 of(), 通过显示值创建一个流。它可以接收任意数量的参数。

- public static<T> Stream<T> of(T... values)：返回一个流

===== 方式四：创建无限流
可以使用静态方法 Stream.iterate() 和 Stream.generate() 创建无限流。

- 迭代 +
public static<T> Stream<T> iterate(final T seed, final UnaryOperator<T> f)
- 生成 +
public static<T> Stream<T> generate(Supplier<T> s) 

==== 中间操作
一个中间操作链，对数据源的数据进行处理。 +
多个中间操作可以连接起来形成一个流水线，除非流水线上触发终止操作，否则中间操作不会执行任何的处理！而在终止操作时一次性全部处理，称为“惰性求值”。

===== 筛选与切片
. filter(Predicate p)：接收 Lambda ， 从流中排除某些元素。
. distinct()：筛选，通过流所生成元素的 hashCode() 和 equals() 去除重复元素。
. limit(long maxSize)：截断流，使其元素不超过给定数量。
. skip(long n)：跳过元素，返回一个扔掉了前 n 个元素的流。若流中元素不足 n 个，则返回一个空流。与 limit(n)互补。

===== 映射
. map(Function f)：接收一个函数作为参数，该函数会被应用到每个元素上，并将其映射成一个新的元素。
. mapToDouble(ToDoubleFunction f)：接收一个函数作为参数，该函数会被应用到每个元素上，产生一个新的 DoubleStream。
. mapToInt(ToIntFunction f)：接收一个函数作为参数，该函数会被应用到每个元素上，产生一个新的 IntStream。
. mapToLong(ToLongFunction f)：接收一个函数作为参数，该函数会被应用到每个元素上，产生一个新的 LongStream。
. flatMap(Function f)：接收一个函数作为参数，将流中的每个值都换成另一个流，然后把所有流连接成一个流。

===== 排序
- sorted()：产生一个新流，其中按自然顺序排序。
- sorted(Comparator com)：产生一个新流，其中按比较器顺序排序。

==== 终止操作(终端操作)
一旦执行终止操作，就执行中间操作链，并产生结果。之后，不会再被使用。

===== 匹配与查找
. allMatch(Predicate p)：检查是否匹配所有元素。
. anyMatch(Predicate p)：检查是否至少匹配一个元素。
. noneMatch(Predicate p)：检查是否没有匹配所有元素。
. findFirst()：返回第一个元素。
. findAny()：返回当前流中的任意元素。
. count()：返回流中元素总数。
. max(Comparator c)：返回流中最大值。
. min(Comparator c)：返回流中最小值。
. forEach(Consumer c)：内部迭代(使用 Collection 接口需要用户去做迭代，称为外部迭代。相反，Stream API 使用内部迭代——它帮你把迭代做了)。

===== 归约
- reduce(T iden, BinaryOperator b)：可以将流中元素反复结合起来，得到一个值。返回 T。
- reduce(BinaryOperator b)：可以将流中元素反复结合起来，得到一个值。返回 Optional<T>。

===== 收集
collect(Collector c)：将流转换为其他形式。接收一个 Collector接口的实现，用于给Stream中元素做汇总的方法。

- 作用：Collector 接口中方法的实现决定了如何对流执行收集的操作(如收集到 List、Set、Map)。

[NOTE]
====
Collectors 实用类提供了很多静态方法，可以方便地创建常见收集器实例。

.常用方法
[%header, cols="3*^.^"]
|===
|方法|返回类型|作用
|toList|List<T>|把流中元素收集到List
|toSet|Set<T>|把流中元素收集到Set
|toCollection|Collection<T>|把流中元素收集到创建的集合
|===

====

== Optional类
=== 引言
到目前为止，臭名昭著的空指针异常是导致Java应用程序失败的最常见原因。 +
以前，为了解决空指针异常，Google公司著名的Guava项目引入了Optional类，Guava通过使用检查空值的方式来防止代码污染，它鼓励程序员写更干净的代码。受到Google Guava的启发，Optional类已经成为Java 8类库的一部分。

=== 作用
解决空指针异常的问题。

Optional<T> 类(java.util.Optional) 是一个容器类，它可以保存类型T的值，代表这个值存在。或者仅仅保存null，表示这个值不存在。原来用 null 表示一个值不存在，现在 Optional 可以更好的表达这个概念。并且可以避免空指针异常。

=== 创建Optional类对象的方法
- Optional.of(T t)：创建一个 Optional 实例，t必须非空。
- Optional.empty()：创建一个空的 Optional 实例。
- Optional.ofNullable(T t)：t可以为null。

=== 判断Optional容器中是否包含对象
- boolean isPresent()：判断是否包含对象。
- void ifPresent(Consumer<? super T> consumer)：如果有值，就执行Consumer接口的实现代码，并且该值会作为参数传给它。

=== 获取Optional容器的对象
- T get(): 如果调用对象包含值，返回该值，否则抛异常
- T orElse(T other)：如果有值则将其返回，否则返回指定的other对象。
- T orElseGet(Supplier<? extends T> other)：如果有值则将其返回，否则返回由Supplier接口实现提供的对象。
- T orElseThrow(Supplier<? extends X> exceptionSupplier)：如果有值则将其返回，否则抛出由Supplier接口实现提供的异常。

=== 示例
.empty的使用
----
// empty():创建的Optional对象内部的value = null
Optional<Object> op1 = Optional.empty();
if(!op1.isPresent()){//Optional封装的数据是否包含数据
    System.out.println("数据为空");
}
System.out.println(op1);
System.out.println(op1.isPresent());
// 如果Optional封装的数据value为空，则get()报错。否则，value不为空时，返回value.
//        System.out.println(op1.get());
----

.of和get方法通常搭配使用
----
String str = "hello";
// str = null;
// of(T t):封装数据t生成Optional对象。要求t非空，否则报错。
Optional<String> op1 = Optional.of(str);
// get()通常与of()方法搭配使用。用于获取内部的封装的数据value
String str1 = op1.get();
System.out.println(str1);
----

.ofNullable和orElse方法通常搭配使用
----
String str = "beijing";
str = null;
// ofNullable(T t) ：封装数据t赋给Optional内部的value。不要求t非空
Optional<String> op1 = Optional.ofNullable(str);
// orElse(T t1):如果Optional内部的value非空，则返回此value值。如果
// value为空，则返回t1.
String str2 = op1.orElse("shanghai");

System.out.println(str2);//
----