= 日志与备份
:source-highlighter: highlight.js
:source-language: sql
:toc: left
:toc-title: 日志与备份
:toclevels: 3
:sectnums:

== 其他数据库日志
=== MySQL支持的日志
==== 日志类型
- 慢查询日志：记录所有执行时间超过long_query_time的所有查询，方便我们对查询进行优化。
- 通用查询日志：记录所有连接的起始时间和终止时间，以及连接发送给数据库服务器的所有指令，对我们复原操作的实际场景、发现问题，甚至是对数据库操作的审计都有很大的帮助。
- 错误日志：记录MySQL服务的启动、运行或停止MySQL服务时出现的问题，方便我们了解服务器的状态，从而对服务器进行维护。
- 二进制日志：记录所有更改数据的语句，可以用于主从服务器之间的数据同步，以及服务器遇到故障时数据的无损失恢复。
- 中继日志：用于主从服务器架构中，从服务器用来存放主服务器二进制日志内容的一个中间文件。从服务器通过读取中继日志的内容，来同步主服务器上的操作。
- 数据定义语句日志：记录数据定义语句执行的元数据操作。

NOTE: 中继日志和数据定义语句日志为MySQL8.0新增。 +
除二进制日志外，其他日志都是文本文件。默认情况下，所有日志创建于MySQL数据目录。

==== 日志的弊端
- 日志功能会降低MySQL数据库的性能。
- 日志会占用大量的磁盘空间。

=== 慢查询日志(slow query log) 
详见link:_g.性能分析工具的使用.pdf[性能分析工具的使用]。

=== 通用查询日志(general query log)
通用查询日志用来 记录用户的所有操作 ，包括启动和关闭MySQL服务、所有用户的连接开始时间和截止时间、发给 MySQL 数据库服务器的所有 SQL 指令等。当我们的数据发生异常时，查看通用查询日志，还原操作时的具体场景，可以帮助我们准确定位问题。

==== 查看当前状态
----
SHOW VARIABLES LIKE '%general%;<1>
----
<1> 默认关闭。

==== 启动日志
===== 方式1：永久性方式
.修改my.cnf或者my.ini配置文件，在[mysqld]组下加入log选项，并重启MySQL服务
----
[mysqld]
general_log=ON
general_log_file=[path[filename]]  #日志文件所在目录路径，filename为日志文件名
----

==== 方式2：临时性方式
.开启通用查询日志
----
SET GLOBAL general_log=on;
----
.设置日志文件保存位置
----
SET GLOBAL general_log_file='path/filename';
----

==== 查看日志
- 通用查询日志是以文本文件的形式存储在文件系统中的，可以使用文本编辑器直接打开日志文件。
- 通用查询日志默认存储在MySQL数据目录中的hostname.log文件中。（hostname表示主机名）

==== 停止日志
===== 方式1：永久性方式
.修改 my.cnf 或者 my.ini 文件
----
[mysqld]
general_log=OFF
# 或
#general_log=ON #直接加注释
----

===== 方式2：临时性方式
----
SET GLOBAL general_log=off;
----

==== 删除\刷新日志
手动删除通用查询日志hostname.log即可。

如果数据的使用非常频繁，那么通用查询日志会占用服务器非常大的磁盘空间。数据管理员可以删除很长时间之前的查询日志，以保证MySQL服务器上的硬盘空间。

.使用如下命令重新生成查询日志文件（前提需开启通用日志）
----
mysqladmin -uroot -p flush-logs
----

=== 错误日志(error log)
==== 启动日志
在MySQL数据库中，错误日志功能是*默认开启*的。错误日志*无法被禁止*。

错误日志默认存储在MySQL数据库的数据文件夹下，名称为mysqld.log （Linux系统）。自定义文件名方法如下：

.在my.cnf或者my.ini中做如下配置
----
[mysqld]
log-error=[path/[filename]]  #path为日志文件所在的目录路径，filename为日志文件名
----

==== 查看日志及其路径
MySQL错误日志是以文本文件形式存储的，可以使用文本编辑器直接查看。

[discrete]
===== 查询错误日志的存储路径
----
SHOW VARIABLES LIKE 'log_err%';
----

==== 删除\刷新日志
直接删除文件。

.重新生成日志文件
----
install -omysql -gmysql -m0644 /dev/null /var/log/mysqld.log

mysqladmin -uroot -p flush-logs
----

=== 二进制日志(bin log)
