= 枚举类
:source-highlighter: highlight.js
:source-language: java
:toc: left
:toc-title: 枚举类
:toclevels: 3
:sectnums:

== 枚举类的使用
- 枚举类的理解：类的对象只有有限个，确定的。我们称此类为枚举类。
- 当需要定义一组常量时，强烈建议使用枚举类。
- 如果枚举类中只有一个对象，则可以作为单例模式的实现方式。

== 如何定义枚举类
=== 方式一：自定义枚举类
==== 说明
. 该方式用于jdk5.0之前。
. 私有化类的构造器，保证不能在类的外部创建其对象。
. 在类的内部创建枚举类的实例，声明为：public static final。
. 对象如果有实例变量，应该声明为private final，并在构造器中初始化。

==== 实例
----
class Season{
    //定义final类型的属性
    private final String seasonName;<1>
    private final String seasonDesc;

    //私有化构造器
    private Season(String seasonName, String seasonDesc){<2>
        this.seasonName = seasonName;
        this.seasonDesc = seasonDesc;
    }

    //创建final类型的静态对象
    public static final Season SPRING = new Season("春天", "春暖花开");<3>
    public static final Season SUMMER = new Season("夏天", "夏日炎炎");
    public static final Season AUTUMN = new Season("秋天", "秋高气爽");
    public static final Season WINTER = new Season("冬天", "冰天雪地");

    //其他
    @Override
    public String toString() {
        return "Season{" +
                "seasonName='" + seasonName + '\'' +
                ", seasonDesc='" + seasonDesc + '\'' +
                '}';
    }

    public String getSeasonName() {
        return seasonName;
    }

    public String getSeasonDesc() {
        return seasonDesc;
    }
}
----
<1> 定义final类型的属性。
<2> 私有化构造器。
<3> 创建final类型的静态对象。

=== [[使用enum关键字定义]]方式二：使用enum关键字定义
==== 说明
. 该方式是jdk5.0新增。
. 使用 enum 定义的枚举类默认继承了 java.lang.Enum类，因此不能再继承其他类。
. 枚举类的构造器只能使用 private 权限修饰符。
. 枚举类的所有实例必须在枚举类中显式列出(, 分隔 ; 结尾)。列出的实例系统会自动添加 public static final 修饰。
. 必须在枚举类的第一行声明枚举类对象。
. **JDK 1.5 中可以在 switch 表达式中使用Enum定义的枚举类的对象作为表达式, case 子句可以直接使用枚举值的名字, 无需添加枚举类作为限定。**

==== 实例
----
interface Info{
    void show();
}
//使用关键字enum创建枚举类
enum Season1 implements Info{
    //首先提供当前枚举类的对象，多个对象之间用","隔开，末尾对象";"结束
    SPRING("春天", "春暖花开"){
        //让枚举类的对象分别实现接口中的抽象方法
        @Override
        public void show() {
            System.out.println("这是春天");
        }
    },
    SUMMER("夏天", "夏日炎炎"){
        @Override
        public void show() {
            System.out.println("这是夏天");
        }
    },
    AUTUMN("秋天", "秋高气爽"){
        @Override
        public void show() {
            System.out.println("这是秋天");
        }
    },
    WINTER("冬天", "冰天雪地"){
        @Override
        public void show() {
            System.out.println("这是冬天");
        }
    };

    private final String seasonName;
    private final String seasonDesc;

    private Season1(String seasonName, String seasonDesc){
        this.seasonName = seasonName;
        this.seasonDesc = seasonDesc;
    }

    public String getSeasonName() {
        return seasonName;
    }

    public String getSeasonDesc() {
        return seasonDesc;
    }
}
----

== Enum类中的常用方法
- values()方法：返回枚举类型的对象数组。该方法可以很方便地遍历所有的枚举值。
- valueOf(String str)：可以把一个字符串转为对应的枚举类对象。要求字符串必须是枚举类对象的“名字”。如不是，会有运行时异常：IllegalArgumentException。
- toString()：返回当前枚举类对象常量的名称
.实例
----
public class SeasonTest1 {
    public static void main(String[] args) {
        Season1 autumn = Season1.AUTUMN;<1>
        System.out.println(autumn);
        Season1[] values = Season1.values();//values()方法
        for (int i = 0; i < values.length; i++) {
            System.out.println(values[i]);
        }
        Season1 summer = Season1.valueOf("SUMMER");//valueOf(String str)
        System.out.println(summer);//toString()
    }
}
----
<1> Season1类见前文<<使用enum关键字定义>>。

== 使用enum关键字定义的枚举类实现接口的情况
=== 情况一
实现接口，在enum类中实现抽象方法。

=== 情况二
让枚举类的对象分别实现接口中的抽象方法。 +
实例，见前文<<使用enum关键字定义>>。

== Enum类中其他的主要方法
[%header, cols="^.^1,^.^2"]
|===
|方法|详细描述
|equals
|在枚举类型中可以直接使用“==”来比较两个枚举常量是否相等。Eum提供的这个equals0方法，也是直接使用“==”实现的。它的存在是为了在Set、List和Map中使用。注意，equals(0是不可变的。

|hashCode
|Enum实现了hashCode()和equals()保持一致。它也是不可变的。

|getDeclaringClass
|得到枚举常量所属枚举类型的Class对象。可以用它来判断两个枚举常量是否属于同一个枚举类型。

|name
|得到当前枚举常量的名称。建议优先使用toString()。

|ordinal
|得到当前枚举常量的次序。

|compareTo
|枚举类型实现了Comparable接口，这样可以比较两个枚举常量的大小（按照声明的顺序排列）

|clone
|枚举类型不能被Clone。为了防止子类实现克隆方法，Enum实现了一个仅抛出CloneNotSupportedException异常的不变Clone()。
|===