= 注解(Annotation)
:source-highlighter: highlight.js
:source-language: java
:toc: left
:toc-title: 注解
:toclevels: 3
:sectnums:

== 概述
. JDK 5.0 增加了对元数据(MetaData) 的支持, 也就是Annotation(注解)。
. Annotation 其实就是代码里的特殊标记, 这些标记可以在编译, 类加载, 运行时被读取, 并执行相应的处理。通过使用 Annotation,程序员可以在不改变原有逻辑的情况下, 在源文件中嵌入一些补充信息。
. Annotation 可以像修饰符一样被使用, 可用于修饰包,类, 构造器, 方法, 成员变量, 参数, 局部变量的声明, 这些信息被保存在 Annotation的 “name=value” 对中。
. 在JavaSE中，注解的使用目的比较简单，例如标记过时的功能，忽略警告等。 +
在JavaEE/Android中注解占据了更重要的角色，例如用来配置应用程序的任何切面，代替JavaEE旧版中所遗留的繁冗代码和XML配置等。

. 未来的开发模式都是基于注解的，JPA是基于注解的，Spring2.5以上都是基于注解的，Hibernate3.x以后也是基于注解的，现在的Struts2有一部分也是基于注解的了，注解是一种趋势，一定程度上可以说：框架 = 注解 + 反射 + 设计模式。

== 常见的Annotation示例
=== 示例一：生成文档相关的注解
. **@author** 标明开发该类模块的作者，多个作者之间使用,分割。
. **@version** 标明该类模块的版本。
. **@see** 参考转向，也就是相关主题。
. **@since** 从哪个版本开始增加的。
. **@param** 对方法中某参数的说明，如果没有参数就不能写。
. **@return** 对方法返回值的说明，如果方法的返回值类型是void就不能写。
. **@exception** 对方法可能抛出的异常进行说明 ，如果方法没有用throws显式抛出的异常就不能写。

其中：

. @param @return 和 @exception 这三个标记都是只用于方法的。
. @param的格式要求：@param 形参名 形参类型 形参说明。
. @return 的格式要求：@return 返回值类型 返回值说明。
. @exception的格式要求：@exception 异常类型 异常说明。
. @param和@exception可以并列多个。

=== 示例二：在编译时进行格式检查(JDK内置的三个基本注解)
- **@Override: **限定重写父类方法, 该注解只能用于方法。
- **@Deprecated: **用于表示所修饰的元素(类, 方法等)已过时。通常是因为所修饰的结构危险或存在更好的选择。
- **@SuppressWarnings: **抑制编译器警告。

=== 跟踪代码依赖性，实现替代配置文件功能
Servlet3.0提供了注解(annotation),使得不再需要在web.xml文件中进行Servlet的部署。

== 自定义Annotation
=== 说明
. 定义新的 Annotation 类型**使用 @interface 关键字**。
. 自定义注解自动继承了java.lang.annotation.Annotation接口。
. Annotation 的**成员变量**在 Annotation 定义中**以无参数方法的形式**来声明。其方法名和返回值定义了该成员的名字和类型。我们称为配置参数。 +
类型只能是八种基本数据类型、String类型、Class类型、enum类型、Annotation类型及以上所有类型的数组。
. 可以在定义 Annotation 的成员变量时为其指定初始值, 指定成员变量的初始值可使用 default 关键字。
. 如果只有一个参数成员，建议使用参数名为value。
. 如果定义的注解**含有配置参数**，那么使用时**必须指定参数值，除非它有默认值**。格式是“参数名 = 参数值”，如果只有一个参数成员，且名称为value，**可以省略“value=”**。
. 没有成员定义的 Annotation 称为标记; 包含成员变量的 Annotation 称为元数据 Annotation。

注意：自定义注解必须配上注解的信息处理流程才有意义。

NOTE: 自定义Annotation可以参照@SuppressWarnings定义。

=== 实例
----
//自定义
public @interface MyAnnotation {

    String value() default "hello";//默认为hello
}

//使用
@MyAnnotation(value="hi")//有默认值时括号内可为空，也可省略“value=”，写作 @MyAnnotation("hi")
class Demo{

}
----

== JDK 中的元注解
=== 概念
元注解：对现有的注解进行解释说明的注解。

=== JDK5.0中的四个元注解
==== @Retention
只能用于修饰一个 Annotation 定义, 用于指定该 Annotation 的生命周期, @Rentention 包含一个 RetentionPolicy 类型的成员变量, 使用@Rentention 时必须为该 value 成员变量指定值：

- **RetentionPolicy.SOURCE:**在源文件中有效（即源文件保留），编译器直接丢弃这种策略的注释。
- **RetentionPolicy.CLASS:**在class文件中有效（即class保留） ， 当运行 Java 程序时, JVM不会保留注解。 **这是默认值。**
- **RetentionPolicy.RUNTIME:**在运行时有效（即运行时保留），当运行Java 程序时, JVM 会保留注释。程序可以通过反射获取该注释。

.例
----
@Retention(RetentionPolicy.RUNTIME)
----

==== @Target
用于修饰 Annotation 定义, 用于指定被修饰的 Annotation 能用于修饰哪些程序元素。 @Target 也包含一个名为 value 的成员变量。

[%header, cols="^.^1,^.^2,^.^1,^.^2"]
|===
|取值|说明|取值|说明
|CONSTRUCTOR
|用于描述构造器

|PACKAGE
|用于描述包

|FIELD
|用于描述域

|PARAMETER
|用于描述参数

|LOCAL_VARIABLE
|用于描述局部变量

|TYPE
|用于描述类、接口（包括注解类型）或enum声明

|METHOD
|用于描述方法

||
|===

.例
----
@Target({TYPE, FIELD, METHOD, PARAMETER, CONSTRUCTOR, LOCAL_VARIABLE})
----

==== @Documented
用于指定被该元 Annotation 修饰的 Annotation 类将被javadoc 工具提取成文档。默认情况下，javadoc是不包括注解的。

IMPORTANT: 定义为Documented的注解必须设置Retention值为RUNTIME。

==== @Inherited
被它修饰的 Annotation 将具有继承性。如果某个类使用了被 @Inherited 修饰的 Annotation, 则其子类将自动具有该注解。

NOTE: 比如：如果把标有@Inherited注解的自定义的注解标注在类级别上，子类则可以继承父类类级别的注解。 +
实际应用中，使用较少。

== 利用反射获取注解信息
到反射部分时系统讲解。

== JDK8中注解的新特性
=== 概述
Java 8对注解处理提供了两点改进：可重复的注解及可用于类型的注解。 +
此外，反射也得到了加强，在Java8中能够得到方法参数的名称。这会简化标注在方法参数上的注解。

=== 可重复的注解
. 在MyAnnotation上声明@Repeatable，成员值为MyAnnotations.class。
. MyAnnotation的Target和Retention等元注解与MyAnnotations相同。

----
@Inherited
@Retention(RetentionPolicy.RUNTIME)
@Target({TYPE, FIELD, METHOD, PARAMETER, CONSTRUCTOR, LOCAL_VARIABLE,TYPE_PARAMETER,TYPE_USE})
public @interface MyAnnotations {

    MyAnnotation[] value();
}

@Inherited
@Repeatable(MyAnnotations.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({TYPE, FIELD, METHOD, PARAMETER, CONSTRUCTOR, LOCAL_VARIABLE,TYPE_PARAMETER,TYPE_USE})
public @interface MyAnnotation {

    String value() default "hello";
}

//jdk 8之前的写法：
//1.创建MyAnnotations，成员变量写为数组：MyAnnotation[] value();
//2.@MyAnnotations({@MyAnnotation(value="hi"),@MyAnnotation(value="hi")})
@MyAnnotation(value="hi")
@MyAnnotation(value="abc")
class Demo{

}
----
=== 类型注解
元注解@Target的参数类型ElementType枚举值多了两个：TYPE_PARAMETER,TYPE_USE。
在Java 8之前，注解只能是在声明的地方所使用，Java8开始，注解可以应用
在任何地方。

- ElementType.TYPE_PARAMETER 表示该注解能写在类型变量的声明语句中（如：泛型声明）。 +
如： `AnnotationTest<@MyAnnotation String> t = null;`
- ElementType.TYPE_USE 表示该注解能写在使用类型的任何语句中。 +
如： `int a = (@MyAnnotation int) 2L;`
